name: Continuous Integration

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io # Github Container Registry
  REPOSITORY: ${{ github.repository }} # Repository name
  REGISTRY_USERNAME: ${{ github.actor }} # Github username
  REGISTRY_PASSWORD: ${{ secrets.GHCR }} # Personal access token

jobs:
  nginx:
    runs-on: ubuntu-latest

    env:
      DOCKERFILE_LOCATION: nginx # Path to Dockerfile directory in the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker login
        run: docker login --username ${{ env.REGISTRY_USERNAME }} --password ${{ env.REGISTRY_PASSWORD }} ${{ env.REGISTRY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build ${{ env.DOCKERFILE_LOCATION }} \
            --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }} \
            --push
